restaurant_assist/config/routes.rb
RestaurantAssist::Application.routes.draw do
  resources :items

  resources :menus

  root :to => 'application#index'

end

restaurant_assist/app/models/item.rb
class Item < ActiveRecord::Base
end

restaurant_assist/app/models/menu.rb
class Menu < ActiveRecord::Base
end

restaurant_assist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

restaurant_assist/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

restaurant_assist/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])
    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :ok }
    end
  end
end

restaurant_assist/app/helpers/application_helper.rb
module ApplicationHelper
end

restaurant_assist/app/helpers/items_helper.rb
module ItemsHelper
end

restaurant_assist/app/helpers/menus_helper.rb
module MenusHelper
end

restaurant_assist/app/views/application/index.html.erb
<div class="row">
	<div class="eight columns">
		<p></p>
		<iframe src="http://player.vimeo.com/video/33683303?title=0&amp;byline=0&amp;portrait=0" width="640" height="480" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
	</div>
	<div class="four columns">
		<p></p>
			<h2><%= PRODUCT_NAME %></h2>
			<div class="company_name">from <%=COMPANY_NAME%></div>
	</div>
</div>

restaurant_assist/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

restaurant_assist/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

restaurant_assist/app/views/items/index.html.erb
<div class="row">
<div class="twelve columns page_header">
	<%= link_to 'New Item', new_item_path, :class=>'right' %>
	<h2>Available items</h2>
</div>
<% @items.each do |items| %>
	<div class="three columns menu items">
		<h4><%= item.name%></h4>
		<h2><%= item.price %></h2>
		<div class="right" style="margin-top:50px">
			<%= link_to 'Show', menu  %>
			<%= link_to 'Edit', edit_menu_path(menu)%>
			<%= link_to 'Delete', menu, confirm: 'Are you sure you want to remove this menu?', method: :delete%>
		</div>
	</div>
<% end %>
</div>

restaurant_assist/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

restaurant_assist/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

restaurant_assist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || Mobipay%></title>
	<link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" id="header">
	<div class="row">
		<div class="four columns">
			<a href="<%=SITE_URL %>">
				<h1><%= PRODUCT_NAME%></h1>
			</a>
		</div>
		<div class="eight columns hide-on-phones">
		      	<strong class="right">
		      		<a href="#">About us</a>
		      		<a href="#">Case Studies</a>
		      		<a href="#">Developers</a>
		      		<a class="small blue nice button src-download">Get your wallet</a>
				</strong>
		</div>
	</div>
</div>
<div class="container">
<%= yield %>
</div>
<footer class="row">
	    <section class="five columns">
	      <h6><strong>Made by <%= COMPANY_NAME%></strong></h6>
        <p><%= PRODUCT_INFO%></p>
	    </section>
	    
	    <section class="three columns">
	      <h6><strong>Using <%=PRODUCT_NAME%>?</strong></h6>
	      <p>Let us know how you're using <%=PRODUCT_NAME%> and we might feature you as an example! <a href="#">Get in touch →</a></p>
	    </section>
	    
	    <section class="four columns">
	      <h6><strong>Need some help?</strong></h6>
	      <p>For quick answers or help <a href="#">email us →</a></p>
	      
	      <ul class="block-grid three-up">
	      	<li>
		      <!-- Place this tag where you want the +1 button to render -->
				<!--div id="___plusone_0" style="height: 20px; width: 90px; display: inline-block; text-indent: 0px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: transparent; border-top-style: none; border-right-style: none; border-bottom-style: none; border-left-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; background-position: initial initial; background-repeat: initial initial; "><iframe allowtransparency="true" frameborder="0" hspace="0" id="I1_1324072128895" marginheight="0" marginwidth="0" name="I1_1324072128895" scrolling="no" src="https://plusone.google.com/_/+1/fastbutton?url=http%3A%2F%2Ffoundation.zurb.com%2Fdocs%2Fgems.php%23rails&amp;size=medium&amp;count=true&amp;annotation=&amp;hl=en-US&amp;jsh=m%3B%2F_%2Fapps-static%2F_%2Fjs%2Fwidget%2F__features__%2Frt%3Dj%2Fver%3DU5kGh5SKuHI.en_GB.%2Fsv%3D1%2Fam%3D!4EfSXeE4ZPeIc6DnWw%2Fd%3D1%2F#id=I1_1324072128895&amp;parent=http%3A%2F%2Ffoundation.zurb.com&amp;rpctoken=267427486&amp;_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe" style="width: 90px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; border-top-style: none; border-right-style: none; border-bottom-style: none; border-left-style: none; height: 20px; position: static; left: 0px; top: 0px; visibility: visible; " tabindex="-1" vspace="0" width="100%" title="+1"></iframe></div-->
				
				<!-- Place this render call where appropriate -->
				<script>
				 // (function() {
				   // var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				    //po.src = 'https://apis.google.com/js/plusone.js';
				    //var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
				  //})();
				</script>
			</li>
			<li>
			
	      		<!--iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/follow_button.html?screen_name=foundationzurb" style="width:80px; height:20px;"></iframe-->
			</li>
			<li>
				<!--iframe src="http://www.facebook.com/plugins/like.php?app_id=273982815961057&amp;href=foundation.zurb.com&amp;send=false&amp;layout=button_count&amp;width=90&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=lucida+grande&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowtransparency="true"></iframe-->
			</li>
		</ul></section></footer>
</body>
</html>

restaurant_assist/app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

restaurant_assist/app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

restaurant_assist/app/views/menus/index.html.erb
<div class="row">
<div class="twelve columns page_header">
	<%= link_to 'Create New Menu', new_menu_path, :class=>'right' %>
	<h2>Available menus</h2>
</div>
<% @menus.each do |menu| %>
	<div class="three columns menu items">
		<h4><%= menu.name%></h4>
		<div class="right" style="margin-top:50px">
			<%= link_to 'Show', menu  %>
			<%= link_to 'Edit', edit_menu_path(menu)%>
			<%= link_to 'Delete', menu, confirm: 'Are you sure you want to remove this menu?', method: :delete%>
		</div>
	</div>

<%end%>
</div>

restaurant_assist/app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

restaurant_assist/app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>